name: Deploy (CI build + upload)

on:
  push:
    branches: ["main"]

permissions:
  contents: read

concurrency:
  group: deploy-main
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build (clean)
        run: npm run build:clean

      - name: Prepare remote paths (clean staging & dest)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          command_timeout: 30m
          script: |
            set -euo pipefail
            mkdir -p ${{ secrets.PROD_REPO }}/dist
            rm -rf ${{ secrets.PROD_REPO }}/dist/*
            sudo mkdir -p ${{ secrets.PROD_PATH }}
            sudo rm -rf ${{ secrets.PROD_PATH }}/*

      - name: Upload dist via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          source: "dist/*"
          target: "${{ secrets.PROD_REPO }}/dist"
          overwrite: true

      - name: Publish to web root via rsync
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script_stop: true
          command_timeout: 30m
          script: |
            set -euo pipefail
            sudo rsync -av --delete ${{ secrets.PROD_REPO }}/dist/ ${{ secrets.PROD_PATH }}
