name: Deploy to VPS

on:
  push:
    branches: ['main']
  workflow_dispatch:

concurrency:
  group: deploy-prod
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      SITE_URL: ${{ secrets.SITE_URL }}
      SITE_DOMAIN: ${{ secrets.SITE_DOMAIN }}
      PUBLIC_GTM_ID: ${{ secrets.PUBLIC_GTM_ID }}
      PUBLIC_ADSENSE_CLIENT: ${{ secrets.PUBLIC_ADSENSE_CLIENT }}
      PUBLIC_ADSENSE_SLOT_BLOG_MID: ${{ secrets.PUBLIC_ADSENSE_SLOT_BLOG_MID }}
      PUBLIC_ADSENSE_SLOT_BLOG_END: ${{ secrets.PUBLIC_ADSENSE_SLOT_BLOG_END }}
      PUBLIC_ADSENSE_SLOT_DL_MID: ${{ secrets.PUBLIC_ADSENSE_SLOT_DL_MID }}
      PUBLIC_ADSENSE_SLOT_DL_END: ${{ secrets.PUBLIC_ADSENSE_SLOT_DL_END }}
      IMAGE_SERVICE: ${{ secrets.IMAGE_SERVICE }}
      MINIFY_ENGINE: ${{ secrets.MINIFY_ENGINE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:clean

      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Ensure remote directory exists
        run: |
          ssh -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "sudo mkdir -p '${{ secrets.DEPLOY_TARGET_DIR }}' && sudo chown root:root '${{ secrets.DEPLOY_TARGET_DIR }}' && sudo chmod 755 '${{ secrets.DEPLOY_TARGET_DIR }}'"

      - name: Rsync dist to server
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.SSH_PORT }}" \
            --rsync-path="sudo rsync" \
            ./dist/ "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_TARGET_DIR }}/"
