name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    if: ${{ !contains(github.event.head_commit.message, '[skip deploy]') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /var/www/astro/erland.me
            git pull origin main
            export IMAGE_SERVICE=passthrough
            export NODE_ENV=production
            npm ci
            npm run build:clean