name: Rollback Deployment

on:
  workflow_dispatch:
    inputs:
      target_sha:
        description: 'Target release SHA (empty for previous)'
        required: false
        default: ''

permissions:
  contents: read

jobs:
  rollback:
    runs-on: ubuntu-latest
    environment:
      name: Production
      url: ${{ vars.SITE_URL }}
    env:
      SITE_URL: ${{ vars.SITE_URL }}
      SSH_OPTS: -o BatchMode=yes -o ConnectTimeout=30 -o ConnectionAttempts=3 -o ServerAliveInterval=15 -o ServerAliveCountMax=3 -o StrictHostKeyChecking=yes -o AddressFamily=inet -o PreferredAuthentications=publickey
    steps:
      # --- SSH setup ---
      - name: Start ssh-agent and add key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          set -euo pipefail
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      # --- List available releases ---
      - name: Show available releases (top ${{ vars.KEEP_RELEASES }})
        run: |
          set -euo pipefail
          # List releases sorted by newest first, then show only the top N
          ssh -p "${{ secrets.SSH_PORT }}" $SSH_OPTS "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" \
            "ls -1dt ${{ vars.DEPLOY_BASE_DIR }}/releases/*/ 2>/dev/null | head -n ${{ vars.KEEP_RELEASES }} || true"

      # --- Execute rollback ---
      - name: Rollback
        env:
          TARGET_SHA: ${{ github.event.inputs.target_sha }}
        run: |
          set -euo pipefail
          # Build rollback command: use specific SHA if provided, otherwise fallback to previous release
          CMD="sudo astro-rollback"
          if [[ -n "${TARGET_SHA}" ]]; then
            CMD="$CMD --to ${TARGET_SHA}"
          else
            CMD="$CMD --previous"
          fi
          # Show command and execute it on the remote host
          echo "Running: $CMD"
          ssh -p "${{ secrets.SSH_PORT }}" $SSH_OPTS "${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}" "$CMD"

      # --- HTTP Health checks after rollback ---
      - name: Verify rollback success
        run: |
          set -euo pipefail
          ROOT_URL="${{ env.SITE_URL }}"
          echo "Waiting 5 seconds for rollback to complete..."
          sleep 5
          # Verify site is accessible after rollback
          STATUS="$(curl -fsS -o /dev/null -w "%{http_code}" -L --max-time 15 --retry 5 --retry-connrefused -H "Cache-Control: no-cache" "${ROOT_URL}/?t=$(date +%s)")"
          test "$STATUS" -eq 200 || { echo "❌ Site not accessible after rollback (HTTP $STATUS)"; exit 1; }
          echo "✅ Rollback successful - site is accessible"
