name: Deploy to Staging

# --- Triggers: automatic on push to staging/testing; manual via workflow_dispatch ---
on:
  push:
    branches:
      - staging
      - testing
    paths:
      - 'astro.config.ts'
      - 'content.config.ts'
      - 'package.json'
      - 'package-lock.json'
      - 'src/**'
      - 'scripts/**'
  workflow_dispatch:

# --- Concurrency: ensure only one staging deploy per branch runs at a time ---
concurrency:
  group: pages-staging-${{ github.ref }}
  cancel-in-progress: true

# --- Jobs: build and publish to Cloudflare Pages ---
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment:
      name: Staging
      url: ${{ env.SITE_URL }}
    # --- Minimal permissions required for this job ---
    permissions:
      contents: read
      deployments: write

    # --- Environment variables used by build and Cloudflare Pages ---
    env:
      SITE_URL: ${{ vars.SITE_URL }}
      SITE_DOMAIN: ${{ vars.SITE_DOMAIN }}
      ENABLE_MINIFY: ${{ vars.ENABLE_MINIFY }}
      PUBLIC_SITE_ENV: ${{ vars.PUBLIC_SITE_ENV }}
      CLOUDFLARE_PROJECT_NAME: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

    steps:
      # --- Repository checkout ---
      - name: Checkout
        uses: actions/checkout@v4

      # --- Validate required staging environment secrets/vars are available ---
      - name: Preflight env availability
        run: |
          set -euo pipefail
          # Validate Environment 'Staging' secrets/vars are mapped into job env
          for v in CLOUDFLARE_ACCOUNT_ID CLOUDFLARE_API_TOKEN CLOUDFLARE_PROJECT_NAME; do
            if [ -z "${!v:-}" ]; then
              echo "❌ Missing $v (ensure Environment 'Staging' secrets/vars exist and names match)"
              echo "Required: secrets.CLOUDFLARE_ACCOUNT_ID, secrets.CLOUDFLARE_API_TOKEN, vars.CLOUDFLARE_PROJECT_NAME"
              exit 1
            fi
          done
          echo "✅ Required envs are present for Staging deploy"

      # --- Node.js setup ---
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      # --- Install and build ---
      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:clean

      # --- Verify build output ---
      - name: Verify build output
        run: |
          set -euo pipefail
          test -d dist && test "$(find dist -type f | wc -l)" -gt 0 || { echo "❌ dist is empty"; exit 1; }

      # --- Publish to Cloudflare Pages ---
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ env.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ env.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ env.CLOUDFLARE_PROJECT_NAME }}
          directory: ./dist
          branch: ${{ github.ref_name }}

      # --- Summary ---
      - name: Summary
        if: always()
        run: |
          {
            echo "### Cloudflare Pages Staging Deployment"
            echo ""
            echo "- Project: ${{ env.CLOUDFLARE_PROJECT_NAME }}"
            echo "- Branch: ${{ github.ref_name }}"
            echo "- Commit: ${{ github.sha }}"
          } >> "$GITHUB_STEP_SUMMARY"
